### ISSUE TITLE
Moving metadata from fdroiddata to fastlane

### ISSUE THREAD

**Issue by linsui** [AnaelMobilia/NextINpact-Unofficial#310]
There is fastlane metadata in this repo but there is only short_description.txt and the text is too long. Could you please add metadata in https://gitlab.com/fdroid/fdroiddata/-/tree/master/metadata/com.pcinpact and move the short_description.txt to full_description.txt?

**Comment by AnaelMobilia** [comment]
Dear @linsui ,

Thanks for the higlight, [i just update](https://github.com/AnaelMobilia/NextINpact-Unofficial/commit/beab88ca89f22b4d7f89869b9886656552d435b0) the two files of description as requested.

Question for the fdroiddata repository: as i'm already providing informations [from application's source repository](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#ways-of-providing-metadata), i'm not sure having data in fdroiddata repository is needed?

**Comment by linsui** [comment]
Could you please add English descriptions in en-US and French in fr instead?

**Comment by linsui** [comment]
> Question for the fdroiddata repository: as i'm already providing informations [from application's source repository](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#ways-of-providing-metadata), i'm not sure having data in fdroiddata repository is needed?

When the next version with the updated metadata published, please ping me and I'll remove the descriptions from fdroiddata. :)

**Comment by AnaelMobilia** [comment]
Dear @linsui ,

As requested, I ping you as a new version is just published.

Bests regards,
Anael

**Comment by linsui** [comment]
> Could you please add English descriptions in en-US and French in fr instead?

Could you please fix this problem? Currently the French discription is put in the en-US metadata which means everyone can only see the French description.

**Comment by AnaelMobilia** [comment]
@linsui so I need some help in order to put correct information :

- This app is about reading news redacted only in french 😃 
- Translating version informations (changelogs) in english is a non-sense: people need to be able to read french to use the application as all content inside it will be in french.
- Google Play Console report that most of the users of the app are using device on French (France) [aka fr-FR locale].

This is why I used the default (en-US) folder as it will be shown to every user on my understanding of the documentation.

---
As I understand of your request and the fastlane documentation, I may do the following:
- Create a fr-FR folder and put on it a copy of short_description.txt and full_description.txt
- Update (on en-US folder) short_description.txt and full_description.txt and translate current content (+ add information that all content of the app will be in french).
- As current images (screenshot, logo) are not linked to a language, let them on the en-US folder as the default/fallback folder.
- As changelog folder will not be translated, I need to let it on en-US? Or can I have it on the fr-FR folder only?

Regards,

**Comment by linsui** [comment]
I want it to have English description so that most users can know what this app is. I thought you can have the changelog in French only.

**Comment by AnaelMobilia** [comment]
Hello @linsui ,

Requested changes have been made. A new version will be published in some hours.

Could you, please, check that the fastlane informations will be correctly updated on f-droid repo?

Regards

**Comment by linsui** [comment]
Updated, thanks!
